# Inherit settings from the default Yocto reference distro
require conf/distro/poky.conf

# Distro Identity
DISTRO = "edge-platform"
DISTRO_NAME = "Raspberry Pi Edge Platform"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "scarthgap"

# You can also add custom DISTRO_FEATURES here later, for example:
# DISTRO_FEATURES:append = " systemd wimax"
# DISTRO_FEATURES:remove = " wayland"
